include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    prefer_final_locals: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    prefer_single_quotes: true
    unnecessary_null_checks: true
    unnecessary_string_interpolations: true
    lines_longer_than_80_chars: true

analyzer:
  errors:
    invalid_assignment: error
    missing_return: error
    unnecessary_cast: warning
    unused_local_variable: warning
