name: gutenberg_tome
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  auto_route: ^8.2.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  realm: ^3.1.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  generate: true
  uses-material-design: true
